# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyIAxXrqqqI-aXIDfTYE9L0ngj9uzyMV
"""

from google.colab import files
uploaded=files.upload()

!pip install pandas
import pandas as pd
d=pd.read_csv('Titanic-Dataset (1).csv')
d

d.isnull().sum()

d.drop('Cabin',axis=1,inplace=True)

d[d['Embarked'].isnull()]

df=d[~d['Embarked'].isnull()]
df

x=df[df['Age'].isnull()]
y=df[~df['Age'].isnull()]

x

y

df.groupby('Pclass')['Age'].mean()

def ad(x):
  if x==1:
    return 38
  elif x==2:
    return 29
  else:
    return 25

x['Age']=x['Pclass'].apply(ad)

final=pd.concat((x,y),ignore_index=True)
final



final.describe()

import matplotlib.pyplot as plt
import seaborn as sns

numeric_features=['Age','SibSp','Parch','Fare']

for feature in numeric_features:
    plt.figure(figsize=(7,4))
    sns.histplot(final[feature].dropna(), kde=True)
    plt.title(f'Histogram of {feature}')
    plt.xlabel('feature')
    plt.ylabel('Frequency')
    plt.show()

for feature in numeric_features:
    plt.figure(figsize=(7,4))
    sns.boxplot(x=final[feature].dropna())
    plt.title(f'Boxplot of {feature}')
    plt.xlabel('feature')
    plt.show()

sns.pairplot(final[numeric_features].dropna())
plt.suptitle('Pairplot of Numeric Features', y=1.02)
plt.show()

corr=final[numeric_features].corr()
plt.figure(figsize=(7,5))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix Heatmap')
plt.show()

missing=final[numeric_features].isnull().sum()
print('Missing values for numeric features:\n', missing)

for feature in numeric_features:
    q_high=final[feature].quantile(0.99)
    outliers=final[final[feature]>q_high]
    print(f'Potential high outliers in {feature}:')
    print(outliers[[feature]])



sns.barplot(x='Sex', y='Survived', data=final)
plt.title('Survival Rate by Sex')
plt.show()





